---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by m1382.
--- DateTime: 2025/7/31 23:25
---
local voucherId = ARGV[1]

local userId = ARGV[2]

local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId

local orderKey = 'seckill:order:' .. voucherId

--if (tonumber(redis.call('get',stockKey)) <= 0) then
--    return 1
--end
local stock = redis.call('get', stockKey)
if not stock or tonumber(stock) <= 0 then
    return 1
end

if (redis.call('sismember',orderKey, userId) == 1) then
    return 2
end
--3.4 扣库存
redis.call('incrby', stockKey, -1)
--3.5 下单(保存用户)
redis.call('sadd', orderKey, userId)
--3.6发送消息到队列  XADD stream orders * k1 v1 k2 v2 、、、
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId, 'id', orderId)


return 0